// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSSaoqF6BDCt3HWuXhmpKRzZAC0EAWoPI',
    appId: '1:603908914578:web:337a4c144fe687823b954b',
    messagingSenderId: '603908914578',
    projectId: 'robofinal-6694b',
    authDomain: 'robofinal-6694b.firebaseapp.com',
    storageBucket: 'robofinal-6694b.firebasestorage.app',
    measurementId: 'G-FTPG6NXXV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHJijOdLAz35TOH5dm7vEXP6HMCC05jHI',
    appId: '1:603908914578:android:04593a5e491a18443b954b',
    messagingSenderId: '603908914578',
    projectId: 'robofinal-6694b',
    storageBucket: 'robofinal-6694b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrgcRD3fXd-rc8QUU_kttx1fOgz4FACPI',
    appId: '1:603908914578:ios:24eabbdf4a7a26ec3b954b',
    messagingSenderId: '603908914578',
    projectId: 'robofinal-6694b',
    storageBucket: 'robofinal-6694b.firebasestorage.app',
    iosBundleId: 'com.example.robofinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrgcRD3fXd-rc8QUU_kttx1fOgz4FACPI',
    appId: '1:603908914578:ios:24eabbdf4a7a26ec3b954b',
    messagingSenderId: '603908914578',
    projectId: 'robofinal-6694b',
    storageBucket: 'robofinal-6694b.firebasestorage.app',
    iosBundleId: 'com.example.robofinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSSaoqF6BDCt3HWuXhmpKRzZAC0EAWoPI',
    appId: '1:603908914578:web:926c3b39893d0e733b954b',
    messagingSenderId: '603908914578',
    projectId: 'robofinal-6694b',
    authDomain: 'robofinal-6694b.firebaseapp.com',
    storageBucket: 'robofinal-6694b.firebasestorage.app',
    measurementId: 'G-6E2JKXM23G',
  );

}